name: .NET CD

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal  

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    
    - uses: actions/checkout@v3
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'appsettings.json'
      env:
        ConnectionStrings.Default: ${{ secrets.DB_CONNECTION_STRINGS}}
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY}}
        heroku_app_name: "flyer-app"
        heroku_email: "javierantonio092@gmail.com"
        usedocker: true